// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ODTUDersSecim.Models;

#nullable disable

namespace ODTUDersSecim.Migrations
{
    [DbContext(typeof(ODTUDersSecimDBContext))]
    [Migration("20230827114753_NewMigrationName")]
    partial class NewMigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ODTUDersSecim.Models.AEESubjects", b =>
                {
                    b.Property<int>("SubjectCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectCode"));

                    b.Property<int?>("SubjectCredit")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectLevel")
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.Property<string>("SubjectType")
                        .HasColumnType("text");

                    b.HasKey("SubjectCode");

                    b.ToTable("AEESubjects");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.CengSubjects", b =>
                {
                    b.Property<int>("SubjectCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectCode"));

                    b.Property<int?>("SubjectCredit")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectLevel")
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.Property<string>("SubjectType")
                        .HasColumnType("text");

                    b.HasKey("SubjectCode");

                    b.ToTable("CengSubjects");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.Departments", b =>
                {
                    b.Property<int>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeptCode"));

                    b.Property<string>("DeptFullName")
                        .HasColumnType("text");

                    b.Property<string>("DeptShortName")
                        .HasColumnType("text");

                    b.HasKey("DeptCode");

                    b.ToTable("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
