// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ODTUDersSecim.Models;

#nullable disable

namespace ODTUDersSecim.Migrations
{
    [DbContext(typeof(ODTUDersSecimDBContext))]
    partial class ODTUDersSecimDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ODTUDersSecim.Models.AEESubjects", b =>
                {
                    b.Property<int>("SubjectCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectCode"));

                    b.Property<int?>("SubjectCredit")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectLevel")
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.Property<string>("SubjectType")
                        .HasColumnType("text");

                    b.HasKey("SubjectCode");

                    b.ToTable("AEESubjects");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.CengSubjects", b =>
                {
                    b.Property<int>("SubjectCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectCode"));

                    b.Property<int?>("SubjectCredit")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectLevel")
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.Property<string>("SubjectType")
                        .HasColumnType("text");

                    b.HasKey("SubjectCode");

                    b.ToTable("CengSubjects");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.Departments", b =>
                {
                    b.Property<int>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeptCode"));

                    b.Property<string>("DeptFullName")
                        .HasColumnType("text");

                    b.Property<string>("DeptShortName")
                        .HasColumnType("text");

                    b.HasKey("DeptCode");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.SubjectSections", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectionId"));

                    b.Property<string>("EndChar")
                        .HasColumnType("text");

                    b.Property<string>("EndGrade")
                        .HasColumnType("text");

                    b.Property<string>("GivenDept")
                        .HasColumnType("text");

                    b.Property<float?>("MaxCumGpa")
                        .HasColumnType("real");

                    b.Property<int?>("MaxYear")
                        .HasColumnType("integer");

                    b.Property<float?>("MinCumGpa")
                        .HasColumnType("real");

                    b.Property<int?>("MinYear")
                        .HasColumnType("integer");

                    b.Property<int>("SectionCode")
                        .HasColumnType("integer");

                    b.Property<string>("StartChar")
                        .HasColumnType("text");

                    b.Property<string>("StartGrade")
                        .HasColumnType("text");

                    b.Property<int>("SubjectCode")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectsSubjectCode")
                        .HasColumnType("integer");

                    b.HasKey("SectionId");

                    b.HasIndex("SubjectsSubjectCode");

                    b.ToTable("SubjectSections");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.Subjects", b =>
                {
                    b.Property<int>("SubjectCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectCode"));

                    b.Property<int?>("SubjectCredit")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectLevel")
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.Property<string>("SubjectType")
                        .HasColumnType("text");

                    b.HasKey("SubjectCode");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.SubjectSections", b =>
                {
                    b.HasOne("ODTUDersSecim.Models.Subjects", "Subjects")
                        .WithMany("SubjectSections")
                        .HasForeignKey("SubjectsSubjectCode");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ODTUDersSecim.Models.Subjects", b =>
                {
                    b.Navigation("SubjectSections");
                });
#pragma warning restore 612, 618
        }
    }
}
